[pytorch_study 파일 다운로드](https://drive.google.com/file/d/1ZJ6j0s4anwuPx1erYIdTrBeQ_cHJoWs7/view?usp=drive_link)

위 링크의 압축파일을 다운로드한다.

구글 드라이브에서 pytorch 디렉토리를 만든다.

다운로드한 파일을 pytorch 디렉토리에 업로드 한다.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
%cp /content/drive/MyDrive/'Colab Notebooks'/김성훈교수강좌/pytorch/pytorch_study.zip  ./
#%cp /content/drive/MyDrive/pytorch/pytorch/pytorch_study.zip  ./

In [ ]:
!unzip pytorch_study.zip

Archive:  pytorch_study.zip
  inflating: data-01-test-score.csv  
  inflating: data-02-stock_daily.csv  
  inflating: data-03-diabetes.csv    
  inflating: data-04-zoo.csv         
  inflating: pytorch_01.ipynb        
  inflating: pytorch_lab-02-1&2-linear_regression.ipynb  
  inflating: pytorch_lab-04-2-multi_variable_linear_regression.ipynb  
  inflating: pytorch_lab-04-3-file_input_linear_regression.ipynb  
  inflating: pytorch_lab-05-1-logistic_regression.ipynb  
  inflating: pytorch_lab-05-2-logistic_regression_diabetes.ipynb  
  inflating: pytorch_lab-06-1-softmax_classifier.ipynb  
  inflating: pytorch_lab-06-2-softmax_zoo_classifier.py.ipynb  
  inflating: pytorch_lab-09-1-xor.py.ipynb  
  inflating: pytorch_lab-09-2-xor-nn.py.ipynb  
  inflating: pytorch_lab-10-1-mnist_softmax.py.ipynb  
  inflating: pytorch_lab-10-2-mnist_nn.py.ipynb  
  inflating: pytorch_lab-10-3-mnist_nn_xavier.py.ipynb  
  inflating: pytorch_lab-10-4-mnist_nn_deep.py.ipynb  
  inflating: pytorch_lab-10-5

## pytorch_01_.ipynb

[여기서 복사](https://colab.research.google.com/drive/1omS5tgm2FnkOCDXIPQzAz9Px2ra_Vwic?usp=sharing)

In [ ]:
#초기화 되지않은 Tensor 생성
import torch
x=torch.Tensor(3)
print(x)

tensor([1.2414e+28, 1.2415e+28, 6.7411e+22])


In [ ]:
#초기화 되지않은 Tensor 생성
import torch
x2=torch.Tensor(3,3)
print(x2)

tensor([[-2.5625e-08,  4.4057e-41, -2.5625e-08],
        [ 4.4057e-41,  4.4842e-44,  0.0000e+00],
        [ 8.9683e-44,  0.0000e+00, -8.7609e+11]])


In [1]:
# rand를 통한 a는 0에서 1사이의 uniform distribution random 값으로 선언
import torch
a = torch.rand(3,3)
print(a)

tensor([[0.4862, 0.2012, 0.4551],
        [0.6023, 0.6280, 0.6515],
        [0.0388, 0.1047, 0.2571]])


In [2]:
# randn를 통한 a는 0이고 분산이 1인 normal distribution random 값으로 선언
import torch
a2 = torch.randn(3,3)
print(a2)

tensor([[ 0.1159,  0.4488, -1.0629],
        [ 0.8561, -0.1072,  0.9694],
        [-0.0042,  0.2457,  0.0711]])


In [3]:
import torch
import numpy as np
a = np.array([1,2,3,4])
b = torch.Tensor(a)
print(b)

tensor([1., 2., 3., 4.])


In [6]:
import torch
import numpy as np
a = torch.rand(3,3)
print(a)
print(a.grad)
print(a.grad_fn)

b = a.numpy()
print(b)

tensor([[0.3091, 0.5100, 0.2652],
        [0.8212, 0.6133, 0.5318],
        [0.6440, 0.7548, 0.2957]])
None
None
[[0.30906558 0.51001054 0.2652219 ]
 [0.82121754 0.6133231  0.5318119 ]
 [0.6440109  0.7548166  0.2957059 ]]


In [8]:
import torch
a = torch.rand(3,3)
print(a)
a = a.view(1,1,3,3)
print(a)


tensor([[0.4817, 0.2649, 0.1862],
        [0.7811, 0.9553, 0.7484],
        [0.2079, 0.1040, 0.3640]])
tensor([[[[0.4817, 0.2649, 0.1862],
          [0.7811, 0.9553, 0.7484],
          [0.2079, 0.1040, 0.3640]]]])


In [10]:
import torch
a = torch.randn(1,1,3,3)
b = torch.randn(1,1,3,3)
c = torch.cat((a,b),0)
print(c)
print(c.shape)

tensor([[[[-1.6140,  0.2297,  0.6602],
          [ 0.5292, -0.8971,  1.4542],
          [-0.2194, -0.1905,  0.2475]]],


        [[[ 0.8755, -0.9040, -0.3503],
          [-1.4284, -0.7258,  0.6377],
          [ 1.9212, -0.0262,  0.5320]]]])
torch.Size([2, 1, 3, 3])


In [11]:
import torch
x = torch.rand(3,3)
y = torch.rand(3,3)
if torch.cuda.is_available():
    x=x.cuda()
    y=y.cuda()
    sum=x+y
    printf(sum)
else:
    print("hhhhh")


hhhhh


In [13]:
import torch
a = torch.rand(3,3)
print(a.mean())      # Tensor a의 평균
print(a.sum())       # Tensor a의 원소합
print(a.sum().item())

tensor(0.4393)
tensor(3.9533)
3.9533286094665527


In [14]:
import torch
from torch.autograd import Variable

a=torch.ones(2,2)
print(a)

a=Variable(a, requires_grad=True)
print(a)

print("----a.data------")
print(a.data)
print("----a.grad------")
print(a.grad)
print("----a.grad_fn------")
print(a.grad_fn)


tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
----a.data------
tensor([[1., 1.],
        [1., 1.]])
----a.grad------
None
----a.grad_fn------
None


In [15]:
b=a+2
print(b)

c=b**2
print(c)

out=c.sum()
print(out)

print(out)
out.backward()

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)
tensor(36., grad_fn=<SumBackward0>)
tensor(36., grad_fn=<SumBackward0>)


In [17]:
print("----a.data------")
print(a.data)
print("----a.grad------")
print(a.grad)
print("----a.grad_fn------")
print(a.grad_fn)

print("----b.data------")
print(b.data)
print("----b.grad------")
print(b.grad)
print("----b.grad_fn------")
print(b.grad_fn)


----a.data------
tensor([[1., 1.],
        [1., 1.]])
----a.grad------
tensor([[6., 6.],
        [6., 6.]])
----a.grad_fn------
None
----b.data------
tensor([[3., 3.],
        [3., 3.]])
----b.grad------
None
----b.grad_fn------


/tmp/ipykernel_118201/2489507783.py:11: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(b.grad)


In [18]:
print("----c.data------")
print(c.data)
print("----c.grad------")
print(c.grad)
print("----c.grad_fn------")
print(c.grad_fn)

print("----out.data------")
print(out.data)
print("----out.grad------")
print(out.grad)
print("----out.grad_fn------")
print(out.grad_fn)


----c.data------
tensor([[9., 9.],
        [9., 9.]])
----c.grad------
None
----c.grad_fn------
----out.data------
tensor(36.)
----out.grad------
None
----out.grad_fn------


/tmp/ipykernel_118201/3383184458.py:4: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(c.grad)
/tmp/ipykernel_118201/3383184458.py:11: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for

In [ ]:
import torch
from torch.autograd import Variable

x=torch.ones(3)
x=Variable(x, requires_grad=True)
y=(x**2)
z=y*3
print(z)
grad=torch.Tensor([0,1,10])
z.backward(grad)

print("----x.data------")
print(x.data)
print("----x.grad------")
print(x.grad)
print("----x.grad_fn------")
print(x.grad_fn)


## pytorch_lab-02-1&2-linear_regression.ipynb

In [1]:
# %% [code]
# Lab 2 Linear Regression
import torch
import torch.nn as nn
from torch.autograd import Variable

# %% [markdown]
#list -> torch tensor -> 변수

# %% [code]
torch.manual_seed(777)   # for reproducibility

# X and Y data
x_train = [[1], [2], [3]]
y_train = [[1], [2], [3]]
X = Variable(torch.Tensor(x_train))
Y = Variable(torch.Tensor(y_train))

# Our hypothesis XW+b
# Pytorch에서 쓰는 용어는 Module 하나에 가깝지만,
# 많은 경우 layer나 model 등의 용어도 같이 사용되므로 굳이 구분하여 적어 보았다.

# Layer : Model 또는 Module을 구성하는 한 개의 층, Convolutional Layer, Linear Layer 등이 있다.
# Module : 1개 이상의 Layer가 모여서 구성된 것. Module이 모여 새로운 Module을 만들 수도 있다.
# Model : 여러분이 최종적으로 원하는 것. 당연히 한 개의 Module일 수도 있다.

# 예를 들어 nn.Linear는 한 개의 layer이기도 하며,
# 이것 하나만으로도 module이나 Model을 구성할 수 있다.
# 단순 Linear Model이 필요하다면, model = nn.Linear(1, 1, True)처럼 사용해도 무방하다.
model = nn.Linear(1, 1, bias=True)

# cost criterion
criterion = nn.MSELoss()

# Minimize
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# %% [code]
# Train the model
for step in range(2001):
    # Our hypothesis
    hypothesis = model(X)
    cost = criterion(hypothesis, Y)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if step % 20 == 0:
        print(step, cost.data.numpy(), model.weight.data.numpy(), model.bias.data.numpy())

0 15.86425 [[-0.66408455]] [0.05607617]
20 0.20035125 [[0.5923785]] [0.5717581]
40 0.053143997 [[0.7237281]] [0.5942415]
60 0.047098298 [[0.74739474]] [0.5710139]
80 0.042764813 [[0.7602834]] [0.5446258]
100 0.038839594 [[0.7716461]] [0.51907295]
120 0.035274763 [[0.7823871]] [0.49468252]
140 0.032037094 [[0.792615]] [0.47143465]
160 0.029096605 [[0.8023614]] [0.44927898]
180 0.02642598 [[0.81164974]] [0.42816448]
200 0.024000496 [[0.8205015]] [0.40804225]
220 0.021797627 [[0.8289373]] [0.38886574]
240 0.01979696 [[0.8369767]] [0.37059048]
260 0.017979907 [[0.84463805]] [0.3531741]
280 0.016329652 [[0.85193956]] [0.33657622]
300 0.014830851 [[0.85889786]] [0.3207584]
320 0.013469602 [[0.8655291]] [0.3056839]
340 0.012233323 [[0.87184876]] [0.29131788]
360 0.011110495 [[0.8778714]] [0.27762702]
380 0.010090738 [[0.88361096]] [0.26457956]
400 0.009164563 [[0.8890809]] [0.2521453]
420 0.008323396 [[0.8942937]] [0.24029532]
440 0.0075594424 [[0.89926153]] [0.2290023]
460 0.006865607 [[0.90

## pytorch_lab-04-2-multi_variable_linear_regression.ipynb

In [2]:
#pytorch_lab-04-2-multi_variable_linear_regression.ipynb

# %% [code]
# Lab 4 Multi-variable linear regression
import torch
import torch.nn as nn
from torch.autograd import Variable

torch.manual_seed(777)   # for reproducibility

# X and Y data
x_data = [[73., 80., 75.], [93., 88., 93.],
          [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = Variable(torch.Tensor(x_data))
Y = Variable(torch.Tensor(y_data))

# Our hypothesis XW+b
model = nn.Linear(3, 1, bias=True)

# cost criterion
criterion = nn.MSELoss()

# Minimize
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

# Train the model
for step in range(2001):
    # Our hypothesis
    hypothesis = model(X)
    cost = criterion(hypothesis, Y)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if step % 10 == 0:
        print(step, "Cost: ", cost.data.numpy(), "\nPrediction:\n", hypothesis.data.numpy())


0 Cost:  50211.008 
Prediction:
 [[-44.56713 ]
 [-56.314262]
 [-54.078915]
 [-58.646557]
 [-43.865524]]
10 Cost:  6.1330004 
Prediction:
 [[153.63612]
 [181.9277 ]
 [180.65643]
 [196.97502]
 [137.85663]]
20 Cost:  5.6454573 
Prediction:
 [[154.22714]
 [182.65448]
 [181.36404]
 [197.74625]
 [138.41452]]
30 Cost:  5.6176424 
Prediction:
 [[154.2203 ]
 [182.66263]
 [181.36356]
 [197.7464 ]
 [138.42426]]
40 Cost:  5.5900164 
Prediction:
 [[154.21167]
 [182.66856]
 [181.36098]
 [197.74423]
 [138.43231]]
50 Cost:  5.5625153 
Prediction:
 [[154.20308]
 [182.67451]
 [181.35838]
 [197.74208]
 [138.44035]]
60 Cost:  5.535174 
Prediction:
 [[154.19447]
 [182.68042]
 [181.35577]
 [197.7399 ]
 [138.44833]]
70 Cost:  5.507951 
Prediction:
 [[154.18593]
 [182.68634]
 [181.3532 ]
 [197.73773]
 [138.45633]]
80 Cost:  5.4808993 
Prediction:
 [[154.17741]
 [182.69223]
 [181.35062]
 [197.7356 ]
 [138.46431]]
90 Cost:  5.4540205 
Prediction:
 [[154.16887]
 [182.69807]
 [181.34805]
 [197.73344]
 [138.47223]

## pytorch_lab-04-3-file_input_linear_regression.ipynb

In [4]:
!pwd

/home/donggeonyoon/rocky/Deeplearning/과제


In [6]:
# %% [code]
# Lab 4 Multi-variable linear regression
import torch
import torch.nn as nn
from torch.autograd import Variable
import numpy as np

torch.manual_seed(777)   # for reproducibility

xy = np.loadtxt('/home/donggeonyoon/Downloads/pytorch_study/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print('-------------------------------')
print(y_data.shape, y_data)

x_data = Variable(torch.from_numpy(x_data))
y_data = Variable(torch.from_numpy(y_data))

# Our hypothesis XW+b
model = nn.Linear(3, 1, bias=True)

# cost criterion
criterion = nn.MSELoss()

# Minimize
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

# Train the model
for step in range(2001):
    optimizer.zero_grad()
    # Our hypothesis
    hypothesis = model(x_data)
    cost = criterion(hypothesis, y_data)
    cost.backward()
    optimizer.step()

    if step % 10 == 0:
        print(step, "Cost: ", cost.data.numpy(), "\nPrediction:\n", hypothesis.data.numpy())

# Ask my score
print("Your score will be ", model(Variable(torch.Tensor([[100, 70, 101]]))).data.numpy())
print("Other scores will be ", model(Variable(torch.Tensor([[60, 70, 110], [90, 100, 80]]))).data.numpy())


(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
-------------------------------
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
0 Cost:  45130.13 
Prediction:
 [[-44.56713 ]
 [-56.314262]
 [-54.078915]
 [-58.646557]
 [-43.865524]
 [-32.330593]
 [-42.79801 ]
 [-30.094688]
 [-52.99058 ]
 [-48.81304 ]
 [-42.31041 ]
 [-42.853672]
 [-56.162563]
 [-47.24037 ]
 [-43.38221 ]
 [-56.6595  ]
 [-46.148106]
 [-50.54158 ]
 [-53.159714]

## pytorch_lab-05-1-logistic_regression.ipynb

In [8]:
# Lab 5 Logistic Regression Classifier
import torch
from torch.autograd import Variable
import numpy as np

torch.manual_seed(777)

x_data = np.array([[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]], dtype=np.float32)
y_data = np.array([[0], [0], [0], [1], [1], [1]], dtype=np.float32)

X = Variable(torch.from_numpy(x_data))
Y = Variable(torch.from_numpy(y_data))

# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
linear = torch.nn.Linear(2, 1, bias=True)
sigmoid = torch.nn.Sigmoid()
model = torch.nn.Sequential(linear, sigmoid)

optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

for step in range(10001):
    optimizer.zero_grad()
    hypothesis = model(X)
    # cost/loss function
    cost = -(Y * torch.log(hypothesis) + (1 - Y)
             * torch.log(1 - hypothesis)).mean()
    cost.backward()
    optimizer.step()

    if step % 200 == 0:
        print(step, cost.data.numpy())

# Accuracy computation
predicted = (model(X).data > 0.5).float()
accuracy = (predicted == Y.data).float().mean()
print("\nHypothesis: ", hypothesis.data.numpy(), "\nCorrect (Y): ", predicted.numpy(), "\nAccuracy: ", accuracy.item())

0 1.7122959
200 0.5587416
400 0.48905894
600 0.4521635
800 0.42799506
1000 0.4095371
1200 0.39402437
1400 0.3802476
1600 0.3676312
1800 0.35588047
2000 0.34483218
2200 0.33438912
2400 0.32448757
2600 0.3150817
2800 0.30613574
3000 0.2976197
3200 0.28950712
3400 0.2817742
3600 0.27439907
3800 0.26736107
4000 0.26064113
4200 0.25422108
4400 0.24808387
4600 0.24221385
4800 0.23659587
5000 0.23121582
5200 0.22606055
5400 0.22111769
5600 0.21637553
5800 0.21182323
6000 0.20745058
6200 0.20324798
6400 0.19920637
6600 0.1953174
6800 0.19157308
7000 0.18796611
7200 0.18448943
7400 0.1811365
7600 0.17790122
7800 0.1747778
8000 0.17176087
8200 0.16884524
8400 0.16602616
8600 0.16329902
8800 0.16065966
9000 0.15810405
9200 0.1556284
9400 0.15322906
9600 0.15090273
9800 0.14864624
10000 0.14645647

Hypothesis:  [[0.02947675]
 [0.15709856]
 [0.29876292]
 [0.7841844 ]
 [0.9413274 ]
 [0.9807585 ]] 
Correct (Y):  [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  1.0


## pytorch_lab-05-2-logistic_regression_diabetes.ipynb

In [ ]:
# Lab 5 Logistic Regression Classifier
import torch
from torch.autograd import Variable
import numpy as np

torch.manual_seed(777)  # for reproducibility

xy = np.loadtxt('data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data.shape, y_data.shape)

X = Variable(torch.from_numpy(x_data))
Y = Variable(torch.from_numpy(y_data))

# Hypothesis using sigmoid
linear = torch.nn.Linear(8, 1, bias=True)
sigmoid = torch.nn.Sigmoid()
model = torch.nn.Sequential(linear, sigmoid)

optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

for step in range(10001):
    optimizer.zero_grad()
    hypothesis = model(X)
    # cost/loss function
    cost = -(Y * torch.log(hypothesis) + (1 - Y)
             * torch.log(1 - hypothesis)).mean()
    cost.backward()
    optimizer.step()

    if step % 200 == 0:
        print(step, cost.data.numpy())

# Accuracy computation
predicted = (model(X).data > 0.5).float()
accuracy = (predicted == Y.data).float().mean()
print("\nHypothesis: ", hypothesis.data.numpy(), "\nCorrect (Y): ", predicted.numpy(), "\nAccuracy: ", accuracy)

## pytorch_lab-06-1-softmax_classifier.ipynb

In [21]:
# Lab 6 Softmax Classifier
import torch
from torch.autograd import Variable

torch.manual_seed(777)  # for reproducibility

x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5],
          [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0],
          [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

X = Variable(torch.Tensor(x_data))
Y = Variable(torch.Tensor(y_data))
nb_classes = 3

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
softmax = torch.nn.Softmax()
linear = torch.nn.Linear(4, nb_classes, bias=True)
model = torch.nn.Sequential(linear, softmax)

optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

for step in range(2001):
    optimizer.zero_grad()
    hypothesis = model(X)
    # Cross entropy cost/loss
    cost = -Y * torch.log(hypothesis)
    cost = torch.sum(cost, 1).mean()
    cost.backward()
    optimizer.step()

    if step % 200 == 0:
        print(step, cost.data.numpy())

# Testing & One-hot encoding
print('--------------')
a = model(Variable(torch.Tensor([[1, 11, 7, 9]])))
print(a.data.numpy(), torch.max(a, 1)[1].data.numpy())

print('--------------')
b = model(Variable(torch.Tensor([[1, 3, 4, 3]])))
print(b.data.numpy(), torch.max(b, 1)[1].data.numpy())

print('--------------')
c = model(Variable(torch.Tensor([[1, 1, 0, 1]])))
print(c.data.numpy(), torch.max(c, 1)[1].data.numpy())

print('--------------')
all = model(Variable(torch.Tensor([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]])))
print(all.data.numpy(), torch.max(all, 1)[1].data.numpy())

## pytorch_lab-06-2-softmax_zoo_classifier.py.ipynb

In [3]:
# Lab 6 Softmax Classifier
import torch
from torch.autograd import Variable
import numpy as np
 
torch.manual_seed(777)  # for reproducibility

data_path = '/home/donggeonyoon/Downloads/pytorch_study/data-04-zoo.csv'
# Predicting animal type based on various features
xy = np.loadtxt(data_path, delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
 
print(x_data.shape, y_data.shape)
 
nb_classes = 7  # 0 ~ 6
 
X = Variable(torch.from_numpy(x_data))
Y = Variable(torch.from_numpy(y_data))
 
# one hot encoding
Y_one_hot = torch.zeros(Y.size()[0], nb_classes)
Y_one_hot.scatter_(1, Y.long().data, 1)
Y_one_hot = Variable(Y_one_hot)
print("one_hot", Y_one_hot.data)
 
softmax = torch.nn.Softmax()
model = torch.nn.Linear(16, nb_classes, bias=True)
 
# Cross entropy cost/loss
criterion = torch.nn.CrossEntropyLoss()    # Softmax is internally computed.
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)
 
for step in range(2001):
    optimizer.zero_grad()
    hypothesis = model(X)
    # Label has to be 1D LongTensor
    cost = criterion(hypothesis, Y.long().view(-1))
    cost.backward()
    optimizer.step()
 
    prediction = torch.max(softmax(hypothesis), 1)[1].float()
 
    correct_prediction = (prediction.data == Y.data)
    accuracy = correct_prediction.float().mean()
 
    if step % 100 == 0:
        #print("Step: {:5}\tLoss: {:.3f}\tAcc: {:.2%}".format(step, cost.data[0], accuracy))
        print("Step: {:5}\tLoss: {:.3f}\tAcc: {:.2%}".format(step, cost.item(), accuracy))
 
 
# Let's see if we can predict
pred = torch.max(softmax(hypothesis), 1)[1].float()
 
#for p, y in zip(pred, Y):
#    print("[{}] Prediction: {} True Y: {}".format(bool(p.data[0] == y.data[0]), p.data.int()[0], y.data.int()[0]))

(101, 16) (101, 1)
one_hot tensor([[1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0.

/home/donggeonyoon/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1518: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


Step:   200	Loss: 0.333	Acc: 24.93%
Step:   300	Loss: 0.257	Acc: 24.47%
Step:   400	Loss: 0.211	Acc: 24.47%
Step:   500	Loss: 0.179	Acc: 24.27%
Step:   600	Loss: 0.156	Acc: 24.19%
Step:   700	Loss: 0.138	Acc: 24.21%
Step:   800	Loss: 0.124	Acc: 24.21%
Step:   900	Loss: 0.113	Acc: 24.07%
Step:  1000	Loss: 0.103	Acc: 24.07%
Step:  1100	Loss: 0.095	Acc: 24.07%
Step:  1200	Loss: 0.088	Acc: 24.07%
Step:  1300	Loss: 0.082	Acc: 24.07%
Step:  1400	Loss: 0.077	Acc: 24.07%
Step:  1500	Loss: 0.073	Acc: 24.07%
Step:  1600	Loss: 0.069	Acc: 24.07%
Step:  1700	Loss: 0.065	Acc: 24.07%
Step:  1800	Loss: 0.062	Acc: 24.07%
Step:  1900	Loss: 0.059	Acc: 24.07%
Step:  2000	Loss: 0.056	Acc: 24.07%


## pytorch_lab-09-1-xor.py.ipynb

In [4]:
# Lab 9 XOR
import torch
from torch.autograd import Variable
import numpy as np

torch.manual_seed(777)  # for reproducibility

x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

X = Variable(torch.from_numpy(x_data))
Y = Variable(torch.from_numpy(y_data))

# Hypothesis using sigmoid
linear = torch.nn.Linear(2, 1, bias=True)
sigmoid = torch.nn.Sigmoid()
model = torch.nn.Sequential(linear, sigmoid)

optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

for step in range(10001):
    optimizer.zero_grad()
    hypothesis = model(X)
    # cost/loss function
    cost = -(Y * torch.log(hypothesis) + (1 - Y)
             * torch.log(1 - hypothesis)).mean()
    cost.backward()
    optimizer.step()

    if step % 100 == 0:
        print(step, cost.data.numpy())

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = (model(X).data > 0.5).float()
accuracy = (predicted == Y.data).float().mean()
print("\nHypothesis: ", hypothesis.data.numpy(), "\nCorrect: ", predicted.numpy(), "\nAccuracy: ", accuracy)

0 0.72739744
100 0.6951809
200 0.6938137
300 0.6933774
400 0.6932311
500 0.6931795
600 0.6931602
700 0.6931526
800 0.6931495
900 0.6931482
1000 0.6931476
1100 0.6931474
1200 0.6931473
1300 0.69314724
1400 0.6931472
1500 0.6931472
1600 0.6931472
1700 0.6931472
1800 0.6931472
1900 0.6931471
2000 0.6931472
2100 0.6931472
2200 0.6931472
2300 0.6931472
2400 0.6931472
2500 0.6931472
2600 0.6931472
2700 0.6931472
2800 0.6931472
2900 0.6931472
3000 0.6931472
3100 0.69314724
3200 0.6931472
3300 0.6931472
3400 0.6931472
3500 0.6931472
3600 0.6931472
3700 0.6931472
3800 0.6931472
3900 0.6931472
4000 0.6931472
4100 0.6931472
4200 0.6931472
4300 0.6931472
4400 0.6931472
4500 0.6931472
4600 0.6931472
4700 0.6931472
4800 0.6931472
4900 0.6931472
5000 0.6931472
5100 0.6931472
5200 0.6931472
5300 0.6931472
5400 0.6931472
5500 0.6931472
5600 0.6931472
5700 0.6931472
5800 0.6931472
5900 0.6931472
6000 0.6931472
6100 0.6931472
6200 0.6931472
6300 0.6931472
6400 0.6931472
6500 0.6931472
6600 0.6931472
6700

9-2

In [5]:
# Lab 9 XOR
import torch
from torch.autograd import Variable
import numpy as np

torch.manual_seed(777)  # for reproducibility

x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

X = Variable(torch.from_numpy(x_data))
Y = Variable(torch.from_numpy(y_data))

linear1 = torch.nn.Linear(2, 2, bias=True)
linear2 = torch.nn.Linear(2, 1, bias=True)
sigmoid = torch.nn.Sigmoid()
model = torch.nn.Sequential(linear1, sigmoid, linear2, sigmoid)

optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

for step in range(10001):
    optimizer.zero_grad()
    hypothesis = model(X)
    # cost/loss function
    cost = -(Y * torch.log(hypothesis) + (1 - Y)
             * torch.log(1 - hypothesis)).mean()
    cost.backward()
    optimizer.step()

    if step % 100 == 0:
        print(step, cost.data.numpy())

# Accuracy computation
# True if hypothesis>0.5 else False
predicted = (model(X).data > 0.5).float()
accuracy = (predicted == Y.data).float().mean()
print("\nHypothesis: ", hypothesis.data.numpy(), "\nCorrect: ", predicted.numpy(), "\nAccuracy: ", accuracy)

0 0.7434073
100 0.69318384
200 0.69317234
300 0.69317126
400 0.69317025
500 0.69316936
600 0.6931684
700 0.69316745
800 0.6931666
900 0.6931658
1000 0.69316494
1100 0.69316405
1200 0.6931633
1300 0.6931625
1400 0.6931617
1500 0.693161
1600 0.69316036
1700 0.69315964
1800 0.6931589
1900 0.6931582
2000 0.69315755
2100 0.69315684
2200 0.69315624
2300 0.69315565
2400 0.69315493
2500 0.69315434
2600 0.6931538
2700 0.69315314
2800 0.6931526
2900 0.693152
3000 0.6931515
3100 0.6931509
3200 0.69315034
3300 0.69314975
3400 0.6931492
3500 0.6931487
3600 0.69314814
3700 0.6931476
3800 0.69314706
3900 0.6931465
4000 0.693146
4100 0.6931454
4200 0.6931449
4300 0.6931443
4400 0.69314384
4500 0.69314325
4600 0.6931428
4700 0.6931423
4800 0.69314176
4900 0.6931411
5000 0.6931407
5100 0.6931402
5200 0.69313955
5300 0.693139
5400 0.69313854
5500 0.693138
5600 0.6931374
5700 0.6931369
5800 0.6931362
5900 0.69313574
6000 0.69313514
6100 0.69313455
6200 0.69313395
6300 0.69313335
6400 0.69313276
6500 0.693

In [6]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# 데이터 준비
x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]).astype(float)
y_data = np.array([[0], [1], [1], [0]]).astype(float)

# 모델 설정
model = Sequential()
model.add(Dense(2, input_dim=2, activation='relu'))  # 첫 번째 레이어: 2 -> 2, ReLU 활성화 함수
model.add(Dense(1, activation='sigmoid'))  # 두 번째 레이어: 2 -> 1, Sigmoid 활성화 함수

# 모델 컴파일
model.compile(loss='binary_crossentropy',
              optimizer=tf.keras.optimizers.SGD(learning_rate=0.1),  # PyTorch와 동일한 SGD
              metrics=['accuracy'])

# 모델 학습
model.fit(x_data, y_data, epochs=10000, verbose=0)

# 모델 평가
loss, accuracy = model.evaluate(x_data, y_data)
print(f"Loss: {loss}, Accuracy: {accuracy}")

# 예측 결과
predicted = (model.predict(x_data) > 0.5).astype(float)
print("\nPredicted: ", predicted)


2024-09-15 15:33:31.824733: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-15 15:33:31.891963: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-15 15:33:31.910493: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-15 15:33:31.961505: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-15 15:33:38.053610: W tensorflow/compiler/tf2

KeyboardInterrupt: 

## pytorch_lab-10-1-mnist_softmax.py.ipynb

In [7]:
# Lab 10 MNIST and softmax
import torch
from torch.autograd import Variable
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import random

torch.manual_seed(777)  # reproducibility

# parameters
learning_rate = 0.001
training_epochs = 15
batch_size = 100

# MNIST dataset
mnist_train = dsets.MNIST(root='MNIST_data/',
                          train=True,
                          transform=transforms.ToTensor(),
                          download=True)

mnist_test = dsets.MNIST(root='MNIST_data/',
                         train=False,
                         transform=transforms.ToTensor(),
                         download=True)

# dataset loader
data_loader = torch.utils.data.DataLoader(dataset=mnist_train,
                                          batch_size=batch_size,
                                          shuffle=True)

# model
model = torch.nn.Linear(784, 10, bias=True)

# define cost/loss & optimizer
criterion = torch.nn.CrossEntropyLoss()    # Softmax is internally computed.
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# train my model
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = len(mnist_train) // batch_size

    for i, (batch_xs, batch_ys) in enumerate(data_loader):
        # reshape input image into [batch_size by 784]
        X = Variable(batch_xs.view(-1, 28 * 28))
        Y = Variable(batch_ys)    # label is not one-hot encoded

        optimizer.zero_grad()
        hypothesis = model(X)
        cost = criterion(hypothesis, Y)
        cost.backward()
        optimizer.step()

        avg_cost += cost / total_batch

        #print("[Epoch: {:>4}] cost = {:>.9}".format(epoch + 1, avg_cost.data[0]))
        print("[Epoch: {:>4}] cost = {:>.9}".format(epoch + 1, avg_cost.item()))

print('Learning Finished!')

# Test model and check accuracy
X_test = Variable(mnist_test.test_data.view(-1, 28 * 28).float())
Y_test = Variable(mnist_test.test_labels)

prediction = model(X_test)
correct_prediction = (torch.max(prediction.data, 1)[1] == Y_test.data)
accuracy = correct_prediction.float().mean()
print('Accuracy:', accuracy)

# Get one and predict
r = random.randint(0, len(mnist_test) - 1)
X_single_data = Variable(mnist_test.test_data[r:r + 1].view(-1, 28 * 28).float())
Y_single_data = Variable(mnist_test.test_labels[r:r + 1])

print("Label: ", Y_single_data.data)
single_prediction = model(X_single_data)
print("Prediction: ", torch.max(single_prediction.data, 1)[1])

Failed to download (trying next):
HTTP Error 403: Forbidden



100.0%


Extracting MNIST_data/MNIST/raw/train-images-idx3-ubyte.gz to MNIST_data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100.0%


Extracting MNIST_data/MNIST/raw/train-labels-idx1-ubyte.gz to MNIST_data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100.0%


Extracting MNIST_data/MNIST/raw/t10k-images-idx3-ubyte.gz to MNIST_data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100.0%


Extracting MNIST_data/MNIST/raw/t10k-labels-idx1-ubyte.gz to MNIST_data/MNIST/raw

[Epoch:    1] cost = 0.00383193721
[Epoch:    1] cost = 0.00756483944
[Epoch:    1] cost = 0.011262713
[Epoch:    1] cost = 0.0148329651
[Epoch:    1] cost = 0.0184097514
[Epoch:    1] cost = 0.0219387673
[Epoch:    1] cost = 0.0253228769
[Epoch:    1] cost = 0.028733125
[Epoch:    1] cost = 0.0321555622
[Epoch:    1] cost = 0.0354582742
[Epoch:    1] cost = 0.0386872441
[Epoch:    1] cost = 0.0418963917
[Epoch:    1] cost = 0.0450322591
[Epoch:    1] cost = 0.0480550565
[Epoch:    1] cost = 0.0510193296
[Epoch:    1] cost = 0.0540604591
[Epoch:    1] cost = 0.0568890423
[Epoch:    1] cost = 0.0597280487
[Epoch:    1] cost = 0.062670812
[Epoch:    1] cost = 0.0655979738
[Epoch:    1] cost = 0.0683870167
[Epoch:    1] cost = 0.0710499585
[Epoch:    1] cost = 0.0736647472
[Epoch:    1] cost = 0.0763349682
[Epoch:    1] cost = 0.0788456053
[Epoch:    1] cost = 0.0814582184
[Epoch:    1] cost = 0.0839820504


KeyboardInterrupt: 

## pytorch_lab-10-2-mnist_nn.py.ipynb

In [ ]:
# Lab 10 MNIST and nn
import torch
from torch.autograd import Variable
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import random

torch.manual_seed(777)  # reproducibility

# parameters
learning_rate = 0.001
training_epochs = 15
batch_size = 100

# MNIST dataset
mnist_train = dsets.MNIST(root='MNIST_data/',
                          train=True,
                          transform=transforms.ToTensor(),
                          download=True)

mnist_test = dsets.MNIST(root='MNIST_data/',
                         train=False,
                         transform=transforms.ToTensor(),
                         download=True)

# dataset loader
data_loader = torch.utils.data.DataLoader(dataset=mnist_train,
                                          batch_size=batch_size,
                                          shuffle=True)
# nn layers
linear1 = torch.nn.Linear(784, 256, bias=True)
linear2 = torch.nn.Linear(256, 256, bias=True)
linear3 = torch.nn.Linear(256, 10, bias=True)
relu = torch.nn.ReLU()

# model
model = torch.nn.Sequential(linear1, relu, linear2, relu, linear3)

# define cost/loss & optimizer
criterion = torch.nn.CrossEntropyLoss()    # Softmax is internally computed.
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# train my model
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = len(mnist_train) // batch_size

    for i, (batch_xs, batch_ys) in enumerate(data_loader):
        # reshape input image into [batch_size by 784]
        X = Variable(batch_xs.view(-1, 28 * 28))
        Y = Variable(batch_ys)    # label is not one-hot encoded

        optimizer.zero_grad()
        hypothesis = model(X)
        cost = criterion(hypothesis, Y)
        cost.backward()
        optimizer.step()

        avg_cost += cost / total_batch

        ####print("[Epoch: {:>4}] cost = {:>.9}".format(epoch + 1, avg_cost.data[0]))
        print("[Epoch: {:>4}] cost = {:>.9}".format(epoch + 1, avg_cost.item()))

print('Learning Finished!')

# Test model and check accuracy
X_test = Variable(mnist_test.test_data.view(-1, 28 * 28).float())
Y_test = Variable(mnist_test.test_labels)

prediction = model(X_test)
correct_prediction = (torch.max(prediction.data, 1)[1] == Y_test.data)
accuracy = correct_prediction.float().mean()
print('Accuracy:', accuracy)

# Get one and predict
r = random.randint(0, len(mnist_test) - 1)
X_single_data = Variable(mnist_test.test_data[r:r + 1].view(-1, 28 * 28).float())
Y_single_data = Variable(mnist_test.test_labels[r:r + 1])

print("Label: ", Y_single_data.data)
single_prediction = model(X_single_data)
print("Prediction: ", torch.max(single_prediction.data, 1)[1])

## pytorch_lab-10-3-mnist_nn_xavier.py.ipynb

In [ ]:
# Lab 10 MNIST and Xavier
import torch
from torch.autograd import Variable
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import random
import torch.nn.init

torch.manual_seed(777)  # reproducibility

# parameters
learning_rate = 0.001
training_epochs = 15
batch_size = 100

# MNIST dataset
mnist_train = dsets.MNIST(root='MNIST_data/',
                          train=True,
                          transform=transforms.ToTensor(),
                          download=True)

mnist_test = dsets.MNIST(root='MNIST_data/',
                         train=False,
                         transform=transforms.ToTensor(),
                         download=True)

# dataset loader
data_loader = torch.utils.data.DataLoader(dataset=mnist_train,
                                          batch_size=batch_size,
                                          shuffle=True)
# nn layers
linear1 = torch.nn.Linear(784, 256, bias=True)
linear2 = torch.nn.Linear(256, 256, bias=True)
linear3 = torch.nn.Linear(256, 10, bias=True)
relu = torch.nn.ReLU()

# xavier initializer
torch.nn.init.xavier_uniform(linear1.weight)
torch.nn.init.xavier_uniform(linear2.weight)
torch.nn.init.xavier_uniform(linear3.weight)

# model
model = torch.nn.Sequential(linear1, relu, linear2, relu, linear3)

# define cost/loss & optimizer
criterion = torch.nn.CrossEntropyLoss()    # Softmax is internally computed.
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# train my model
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = len(mnist_train) // batch_size

    for i, (batch_xs, batch_ys) in enumerate(data_loader):
        # reshape input image into [batch_size by 784]
        X = Variable(batch_xs.view(-1, 28 * 28))
        Y = Variable(batch_ys)    # label is not one-hot encoded

        optimizer.zero_grad()
        hypothesis = model(X)
        cost = criterion(hypothesis, Y)
        cost.backward()
        optimizer.step()

        avg_cost += cost / total_batch

        ####    print("[Epoch: {:>4}] cost = {:>.9}".format(epoch + 1, avg_cost.data[0]))
        print("[Epoch: {:>4}] cost = {:>.9}".format(epoch + 1, avg_cost.item()))

print('Learning Finished!')

# Test model and check accuracy
X_test = Variable(mnist_test.test_data.view(-1, 28 * 28).float())
Y_test = Variable(mnist_test.test_labels)

prediction = model(X_test)
correct_prediction = (torch.max(prediction.data, 1)[1] == Y_test.data)
accuracy = correct_prediction.float().mean()
print('Accuracy:', accuracy)

# Get one and predict
r = random.randint(0, len(mnist_test) - 1)
X_single_data = Variable(mnist_test.test_data[r:r + 1].view(-1, 28 * 28).float())
Y_single_data = Variable(mnist_test.test_labels[r:r + 1])

print("Label: ", Y_single_data.data)
single_prediction = model(X_single_data)
print("Prediction: ", torch.max(single_prediction.data, 1)[1])

## pytorch_lab-10-4-mnist_nn_deep.py.ipynb

In [ ]:
# Lab 10 MNIST and Deep learning
import torch
from torch.autograd import Variable
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import random
import torch.nn.init

torch.manual_seed(777)  # reproducibility

# parameters
learning_rate = 0.001
training_epochs = 15
batch_size = 100

# MNIST dataset
mnist_train = dsets.MNIST(root='MNIST_data/',
                          train=True,
                          transform=transforms.ToTensor(),
                          download=True)

mnist_test = dsets.MNIST(root='MNIST_data/',
                         train=False,
                         transform=transforms.ToTensor(),
                         download=True)

# dataset loader
data_loader = torch.utils.data.DataLoader(dataset=mnist_train,
                                          batch_size=batch_size,
                                          shuffle=True)
# nn layers
linear1 = torch.nn.Linear(784, 512, bias=True)
linear2 = torch.nn.Linear(512, 512, bias=True)
linear3 = torch.nn.Linear(512, 512, bias=True)
linear4 = torch.nn.Linear(512, 512, bias=True)
linear5 = torch.nn.Linear(512, 10, bias=True)
relu = torch.nn.ReLU()

# xavier initializer
torch.nn.init.xavier_uniform(linear1.weight)
torch.nn.init.xavier_uniform(linear2.weight)
torch.nn.init.xavier_uniform(linear3.weight)
torch.nn.init.xavier_uniform(linear4.weight)
torch.nn.init.xavier_uniform(linear5.weight)

# model
# nn 패키지를 사용하여 모델과 손실 함수를 정의합니다.
model = torch.nn.Sequential(linear1, relu,
                            linear2, relu,
                            linear3, relu,
                            linear4, relu,
                            linear5)

# define cost/loss & optimizer
# criterion : 기준. 어떤 loss를 줄일 것인지에 대해서 명시한다.
criterion = torch.nn.CrossEntropyLoss()    # Softmax is internally computed.

# optim 패키지를 사용하여 모델의 가중치를 갱신할 Optimizer를 정의합니다.
# 여기서는 Adam을 사용하겠습니다; optim 패키지는 다른 다양한 최적화 알고리즘을
# 포함하고 있습니다. Adam 생성자의 첫번째 인자는 어떤 Tensor가 갱신되어야 하는지
# 알려줍니다.
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# train my model
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = len(mnist_train) // batch_size

    for i, (batch_xs, batch_ys) in enumerate(data_loader):
        # reshape input image into [batch_size by 784]
        X = Variable(batch_xs.view(-1, 28 * 28))
        Y = Variable(batch_ys)    # label is not one-hot encoded

        # 순전파 단계: 모델에 x를 전달하여 예상되는 y 값을 계산합니다.
        # 모든 X 데이터를 매트릭스(행렬) 형태로 모델에게 넘겨준다.
        hypothesis = model(X)

        # 손실을 계산하고 출력합니다.
        # criterion이라는 함수를 통해서 예측과 정답을 비교하는 평가를 진행한다. 
        # 이 때, Cross Entropy Loss 를 criterion에 넣었기 때문에 
        # 그것을 기준으로 진행하게 된다.
        cost = criterion(hypothesis, Y)

        # 역전파 단계 전에, Optimizer 객체를 사용하여 (모델의 학습 가능한 가중치인)
        # 갱신할 변수들에 대한 모든 변화도를 0으로 만듭니다. 이렇게 하는 이유는
        # 기본적으로 .backward()를 호출할 때마다 변화도가 버퍼(buffer)에 (덮어쓰지 않고)
        # 누적되기 때문입니다. 더 자세한 내용은 torch.autograd.backward에 대한 문서를
        # 참조하세요.
        optimizer.zero_grad()

        # 역전파 단계: 모델의 학습 가능한 모든 매개변수에 대해 손실의 변화도를
        # 계산합니다. 내부적으로 각 Module의 매개변수는 requires_grad=True 일 때
        # Tensor 내에 저장되므로, 이 호출은 모든 모델의 모든 학습 가능한 매개변수의
        # 변화도를 계산하게 됩니다.
        cost.backward()

        # Optimizer의 step 함수를 호출하면 매개변수가 갱신됩니다.
        # step()이란 함수를 실행시키면 우리가 미리 선언할 때 
        # 지정해 준 model의 파라미터들이 업데이트 된다.
        optimizer.step()

        avg_cost += cost / total_batch

        #print("[Epoch: {:>4}] cost = {:>.9}".format(epoch + 1, avg_cost.data[0]))
        print("[Epoch: {:>4}] cost = {:>.9}".format(epoch + 1, avg_cost.item()))

print('Learning Finished!')

# Test model and check accuracy
X_test = Variable(mnist_test.test_data.view(-1, 28 * 28).float())
Y_test = Variable(mnist_test.test_labels)

prediction = model(X_test)
correct_prediction = (torch.max(prediction.data, 1)[1] == Y_test.data)
accuracy = correct_prediction.float().mean()
print('Accuracy:', accuracy)

# Get one and predict
r = random.randint(0, len(mnist_test) - 1)
X_single_data = Variable(mnist_test.test_data[r:r + 1].view(-1, 28 * 28).float())
Y_single_data = Variable(mnist_test.test_labels[r:r + 1])

print("Label: ", Y_single_data.data)
single_prediction = model(X_single_data)
print("Prediction: ", torch.max(single_prediction.data, 1)[1])

## pytorch_lab-10-5-mnist_nn_dropout.py .ipynb

In [ ]:
# Lab 10 MNIST and Dropout
import torch
from torch.autograd import Variable
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import random
import torch.nn.init

torch.manual_seed(777)  # reproducibility

# parameters
learning_rate = 0.001
training_epochs = 15
batch_size = 100
keep_prob = 0.7

# MNIST dataset
mnist_train = dsets.MNIST(root='MNIST_data/',
                          train=True,
                          transform=transforms.ToTensor(),
                          download=True)

mnist_test = dsets.MNIST(root='MNIST_data/',
                         train=False,
                         transform=transforms.ToTensor(),
                         download=True)

# dataset loader
data_loader = torch.utils.data.DataLoader(dataset=mnist_train,
                                          batch_size=batch_size,
                                          shuffle=True)
# nn layers
linear1 = torch.nn.Linear(784, 512, bias=True)
linear2 = torch.nn.Linear(512, 512, bias=True)
linear3 = torch.nn.Linear(512, 512, bias=True)
linear4 = torch.nn.Linear(512, 512, bias=True)
linear5 = torch.nn.Linear(512, 10, bias=True)

relu = torch.nn.ReLU()
# p is the probability of being dropped in PyTorch
dropout = torch.nn.Dropout(p=1 - keep_prob)

# xavier initializer
torch.nn.init.xavier_uniform(linear1.weight)
torch.nn.init.xavier_uniform(linear2.weight)
torch.nn.init.xavier_uniform(linear3.weight)
torch.nn.init.xavier_uniform(linear4.weight)
torch.nn.init.xavier_uniform(linear5.weight)

# model
model = torch.nn.Sequential(linear1, relu, dropout,
                            linear2, relu, dropout,
                            linear3, relu, dropout,
                            linear4, relu, dropout,
                            linear5)

# define cost/loss & optimizer
criterion = torch.nn.CrossEntropyLoss()    # Softmax is internally computed.
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# train my model
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = len(mnist_train) // batch_size

    for i, (batch_xs, batch_ys) in enumerate(data_loader):
        # reshape input image into [batch_size by 784]
        X = Variable(batch_xs.view(-1, 28 * 28))
        Y = Variable(batch_ys)    # label is not one-hot encoded

        optimizer.zero_grad()
        hypothesis = model(X)
        cost = criterion(hypothesis, Y)
        cost.backward()
        optimizer.step()

        avg_cost += cost / total_batch

####    print("[Epoch: {:>4}] cost = {:>.9}".format(epoch + 1, avg_cost.data[0]))

print('Learning Finished!')

# Test model and check accuracy
model.eval()    # set the model to evaluation mode (dropout=False)

X_test = Variable(mnist_test.test_data.view(-1, 28 * 28).float())
Y_test = Variable(mnist_test.test_labels)

prediction = model(X_test)
correct_prediction = (torch.max(prediction.data, 1)[1] == Y_test.data)
accuracy = correct_prediction.float().mean()
print('Accuracy:', accuracy)

# Get one and predict
r = random.randint(0, len(mnist_test) - 1)
X_single_data = Variable(mnist_test.test_data[r:r + 1].view(-1, 28 * 28).float())
Y_single_data = Variable(mnist_test.test_labels[r:r + 1])

print("Label: ", Y_single_data.data)
single_prediction = model(X_single_data)
print("Prediction: ", torch.max(single_prediction.data, 1)[1])

## pytorch_lab-11-1-mnist_cnn.ipynb

In [ ]:
# Lab 11 MNIST and Convolutional Neural Network
import torch
from torch.autograd import Variable
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import torch.nn.init

torch.manual_seed(777)  # reproducibility

# parameters
learning_rate = 0.001
training_epochs = 15
batch_size = 100

# MNIST dataset
mnist_train = dsets.MNIST(root='MNIST_data/',
                          train=True,
                          transform=transforms.ToTensor(),
                          download=True)

mnist_test = dsets.MNIST(root='MNIST_data/',
                         train=False,
                         transform=transforms.ToTensor(),
                         download=True)

# dataset loader
data_loader = torch.utils.data.DataLoader(dataset=mnist_train,
                                          batch_size=batch_size,
                                          shuffle=True)

# CNN Model (2 conv layers)


class CNN(torch.nn.Module):

    def __init__(self):
        super(CNN, self).__init__()
        # L1 ImgIn shape=(?, 28, 28, 1)
        #    Conv     -> (?, 28, 28, 32)
        #    Pool     -> (?, 14, 14, 32)
        self.layer1 = torch.nn.Sequential(
            torch.nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1),
            torch.nn.ReLU(),
            torch.nn.MaxPool2d(kernel_size=2, stride=2))
        
        # L2 ImgIn shape=(?, 14, 14, 32)
        #    Conv      ->(?, 14, 14, 64)
        #    Pool      ->(?, 7, 7, 64)
        self.layer2 = torch.nn.Sequential(
            torch.nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
            torch.nn.ReLU(),
            torch.nn.MaxPool2d(kernel_size=2, stride=2))

        # Final FC 7x7x64 inputs -> 10 outputs
        self.fc = torch.nn.Linear(7 * 7 * 64, 10, bias=True)
        torch.nn.init.xavier_uniform(self.fc.weight)

    def forward(self, x):
        out = self.layer1(x)
        out = self.layer2(out)
        out = out.view(out.size(0), -1)   # Flatten them for FC
        out = self.fc(out)
        return out


# instantiate CNN model
model = CNN()

# define cost/loss & optimizer
criterion = torch.nn.CrossEntropyLoss()    # Softmax is internally computed.
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# train my model
print('Learning started. It takes sometime.')
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = len(mnist_train) // batch_size

    for i, (batch_xs, batch_ys) in enumerate(data_loader):
        X = Variable(batch_xs)    # image is already size of (28x28), no reshape
        Y = Variable(batch_ys)    # label is not one-hot encoded

        optimizer.zero_grad()
        hypothesis = model(X)
        cost = criterion(hypothesis, Y)
        cost.backward()
        optimizer.step()

        avg_cost += cost.data / total_batch

        #####    print("[Epoch: {:>4}] cost = {:>.9}".format(epoch + 1, avg_cost[0]))
        if ((i % 100) == 0):
          print("[Epoch: {:>4}] cost = {:>.9}".format(epoch + 1, avg_cost))

print('Learning Finished!')

# Test model and check accuracy
model.eval()    # set the model to evaluation mode (dropout=False)

X_test = Variable(mnist_test.test_data.view(len(mnist_test), 1, 28, 28).float())
Y_test = Variable(mnist_test.test_labels)

prediction = model(X_test)
correct_prediction = (torch.max(prediction.data, 1)[1] == Y_test.data)
accuracy = correct_prediction.float().mean()
print('Accuracy:', accuracy)

## pytorch_lab-11-2-mnist_deep_cnn.py.ipynb

In [ ]:
# Lab 11 MNIST and Deep learning CNN
import torch
from torch.autograd import Variable
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import torch.nn.init

torch.manual_seed(777)  # reproducibility

# parameters
learning_rate = 0.001
training_epochs = 15
batch_size = 100
keep_prob = 0.7

# MNIST dataset
mnist_train = dsets.MNIST(root='MNIST_data/',
                          train=True,
                          transform=transforms.ToTensor(),
                          download=True)

mnist_test = dsets.MNIST(root='MNIST_data/',
                         train=False,
                         transform=transforms.ToTensor(),
                         download=True)

# dataset loader
data_loader = torch.utils.data.DataLoader(dataset=mnist_train,
                                          batch_size=batch_size,
                                          shuffle=True)

# CNN Model


class CNN(torch.nn.Module):

    def __init__(self):
        super(CNN, self).__init__()
        # L1 ImgIn shape=(?, 28, 28, 1)
        #    Conv     -> (?, 28, 28, 32)
        #    Pool     -> (?, 14, 14, 32)
        self.layer1 = torch.nn.Sequential(
            torch.nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1),
            torch.nn.ReLU(),
            torch.nn.MaxPool2d(kernel_size=2, stride=2),
            torch.nn.Dropout(p=1 - keep_prob))
        # L2 ImgIn shape=(?, 14, 14, 32)
        #    Conv      ->(?, 14, 14, 64)
        #    Pool      ->(?, 7, 7, 64)
        self.layer2 = torch.nn.Sequential(
            torch.nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
            torch.nn.ReLU(),
            torch.nn.MaxPool2d(kernel_size=2, stride=2),
            torch.nn.Dropout(p=1 - keep_prob))
        # L3 ImgIn shape=(?, 7, 7, 64)
        #    Conv      ->(?, 7, 7, 128)
        #    Pool      ->(?, 4, 4, 128)
        self.layer3 = torch.nn.Sequential(
            torch.nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1),
            torch.nn.ReLU(),
            torch.nn.MaxPool2d(kernel_size=2, stride=2, padding=1),
            torch.nn.Dropout(p=1 - keep_prob))

        # L4 FC 4x4x128 inputs -> 625 outputs
        self.fc1 = torch.nn.Linear(4 * 4 * 128, 625, bias=True)
        torch.nn.init.xavier_uniform(self.fc1.weight)
        self.layer4 = torch.nn.Sequential(
            self.fc1,
            torch.nn.ReLU(),
            torch.nn.Dropout(p=1 - keep_prob))
        # L5 Final FC 625 inputs -> 10 outputs
        self.fc2 = torch.nn.Linear(625, 10, bias=True)
        torch.nn.init.xavier_uniform(self.fc2.weight)

    def forward(self, x):
        out = self.layer1(x)
        out = self.layer2(out)
        out = self.layer3(out)
        out = out.view(out.size(0), -1)   # Flatten them for FC
        out = self.fc1(out)
        out = self.fc2(out)
        return out


# instantiate CNN model
model = CNN()

# define cost/loss & optimizer
criterion = torch.nn.CrossEntropyLoss()    # Softmax is internally computed.
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# train my model
print('Learning started. It takes sometime.')
for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = len(mnist_train) // batch_size

    for i, (batch_xs, batch_ys) in enumerate(data_loader):
        X = Variable(batch_xs)    # image is already size of (28x28), no reshape
        Y = Variable(batch_ys)    # label is not one-hot encoded

        optimizer.zero_grad()
        hypothesis = model(X)
        cost = criterion(hypothesis, Y)
        cost.backward()
        optimizer.step()

        avg_cost += cost.data / total_batch

        #print("[Epoch: {:>4}] cost = {:>.9}".format(epoch + 1, avg_cost[0]))
        print("[Epoch: {:>4}] cost = {:>.9}".format(epoch + 1, avg_cost))

print('Learning Finished!')

# Test model and check accuracy
model.eval()    # set the model to evaluation mode (dropout=False)

X_test = Variable(mnist_test.test_data.view(len(mnist_test), 1, 28, 28).float())
Y_test = Variable(mnist_test.test_labels)

prediction = model(X_test)
correct_prediction = (torch.max(prediction.data, 1)[1] == Y_test.data)
accuracy = correct_prediction.float().mean()
print('Accuracy:', accuracy)

## pytorch_lab-11-2-mnist_deep_cnn.py.ipynb

## pytorch_lab-11-2-mnist_deep_cnn.py.ipynb

## pytorch_lab-11-2-mnist_deep_cnn.py.ipynb

## pytorch_lab-10-2-mnist_nn.py.ipynb